package assignment;

import java.util.*;

class AddNumber extends Exception {
	AddNumber() {

	}

}

public class ExceptionClass {
	public static void main(String args[]) {
		Scanner sc = new Scanner(System.in);
		int number1;
		int number2;
		int result;
		System.out.println("Enter number 1");
		number1 = sc.nextInt();
		System.out.println("Enter number 2");
		number2 = sc.nextInt();
		result = number1 + number2;
		if (result < 100) {
			System.out.println("The sum is less than 100 ");
			System.out.println("the result is:+result");
		} else {
			try {
				throw new AddNumber();
			} catch (AddNumber a) {
				System.out.println("Exception is caught in catch");
			}
		}

	}
}
